services:
  express-server:
    image: node-docker
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./index.js
        target: /app/index.js
    command: npx nodemon -L index.js

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=proyect_milo
      - POSTGRES_USER=Davidfcg20
      - POSTGRES_PASSWORD=375NegroDF
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=davidfcg@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=proyect_milo
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=375NegroDF
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql

    ports:
      - "8080:80"

volumes:
  postgres_data:
    name: 'postgres_data'
  pgadmin-data:
    name: 'pgadmin-data'
  mysql_data:
    name: 'mysql_data'



